build:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/llm-engine/buildenv-x86_64:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
  - docker
  - x86
  - infiniband 
  script:
  - export HOME=/home/hicr
  - source /home/hicr/.hicr-env.sh
  - echo "Building LLM-Engine..."
  - mkdir build
  - meson setup build -Dbuildtype=debug -Db_coverage=true -DbuildTests=true -DbuildExamples=true -DdistributedEngine=mpi -DbuildInstrumentation=true -DcompileWarningsAsErrors=true
  - meson compile -C build
  - echo "Running tests..."
  - meson test -C build
  - echo "Creating coverage report..."
  - ninja -C build coverage
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    when: always
    paths:
      - build/meson-logs/*
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/meson-logs/coverage.xml 
  only:
  - main
  - merge_requests
  - tags

docs:
  image: registry.gitlab.huaweirc.ch/zrc-von-neumann-lab/runtime-system-innovations/hicr/docs:latest
  tags:
  - docker
  - tiny
  script:
  - echo "Checking TaskR source and test formatting..."
  - .build-tools/style/check-style.sh check include
  - .build-tools/style/check-style.sh check tests
  - .build-tools/style/check-style.sh check examples
  - echo "Building code documentation..."
  - make -j1 -C docs
  only: 
  - main
  - merge_requests
  - tags

