name: Merge into master - Build and Run Tests

# if statements modified to avoid: https://stackoverflow.com/questions/69354003/github-action-job-fire-when-previous-job-skipped

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  DOCKERIMAGE: ghcr.io/algebraic-programming/hicr/buildenv

jobs:
  compile-and-test-arm64:
    uses: Algebraic-Programming/hLLM/.github/workflows/master-test-workflow.yml@main
    with:
      os: ubuntu-24.04-arm
      arch: arm64

  compile-and-test-amd64:
    uses: Algebraic-Programming/hLLM/.github/workflows/master-test-workflow.yml@main
    with:
      os: ubuntu-24.04
      arch: amd64
 