name: PR development - Build and Run Tests

# if statements modified to avoid: https://stackoverflow.com/questions/69354003/github-action-job-fire-when-previous-job-skipped

on:
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  ci-arm64:
    uses: Algebraic-Programming/hLLM/.github/workflows/pr-development-workflow.yml@master
    with:
      os: ubuntu-24.04-arm
      arch: arm64
  
  ci-amd64:
    uses: Algebraic-Programming/hLLM/.github/workflows/pr-development-workflow.yml@master
    with:
      os: ubuntu-24.04
      arch: amd64